### PR TITLE
Fixes #19 checks to see if the target is also empty

### LINKED ISSUE #19: Uncaught error when target element is blank .
If you import a XLIFF document with an empty target e.g.

```<target></target>```

Then the `.FromXliff` function fails as Target.Text is null or empty (so `Target.Text[0]` as PlainText).

_PR on it's way - just wanted issue number for branch_

### PR DESCRIPTION
**Pull request by KevinJump**
Simple fix to check for empty or null text list in target.

### CODE REVIEW

File: XliffLib/Model/Property.cs [hunk 1]
```diff
@@ -22,7 +22,7 @@ public static new PropertyContainer FromXliff(TranslationContainer xliffUnit)
             var segment = unit.Resources[0] as Segment;
 
             //TODO: Add test for this condition
-            if (segment.Target == null)
+            if (segment.Target == null || segment.Target.Text == null | segment.Target.Text.Count == 0)
```
Comment (simonech) [inline XliffLib/Model/Property.cs]: Is the `|` intended or is it a mistake?

**Comment by KevinJump** [comment]
yeah that would be me being stupid :)

**Comment by simonech** [comment]
I guess the actual XSD validation when reading the file should spot this before we arrive at this point, but adding an extra check won't hurt :smile:
